### ISSUE TITLE
Trello Board

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-DOL-WHD-14-c#12]
# Question/Comment on DOL WHD 14(c) RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 2.0, Objectives - [Trello board](https://trello.com/b/74MUGMpP)

## Question/Comment
Two additional cards were added to the Trello board on July 14. Will additional user needs continue to be added to the backlog?  Are these considered to be part of the Scope or Requirements and expected to be completed within the 60 day period of performance?

**Comment by rrefoy** [comment]
The two added boards in Trello were added to match the PWS, additional cards will not be added but will be prioritized with the awardee. Second paragraph of 2.0 states "These user needs shall be met in order to fulfill the objectives for performance of this task order, and may be refined by later sprints to continuously meet user needs."
